transpvis-front:
    command: npm start
    container_name: transpvis-front
    environment:
        - REACT_APP_ENV=dev
        - PORT=3000
    build: .
    ports:
        - "3000:3000"
    volumes:
        - .:/code
        - /code/node_modules
    tty: true
