export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const SET_APPLICATION = "SET_APPLICATION";
export const SET_FOCUSED = "SET_FOCUSED";
export const REMOVE_FOCUSED = "REMOVE_FOCUSED";
export const TOGGLE_LOADING_APPLICATION = "TOGGLE_LOADING_APPLICATION";

export const GET_STAKEHOLDERS = "GET_STAKEHOLDERS";
export const TOGGLE_LOADING_STAKEHOLDERS = "TOGGLE_LOADING_STAKEHOLDERS";
export const GET_INFORMATION_ELEMENTS = "GET_INFORMATION_ELEMENTS";
export const TOGGLE_LOADING_INFORMATION_ELEMENTS =
    "TOGGLE_LOADING_INFORMATION_ELEMENTS";
export const GET_RELATIONS = "GET_RELATIONS";
export const TOGGLE_LOADING_RELATIONS = "TOGGLE_LOADING_RELATIONS";

export const TOGGLE_HELP = "TOGGLE_HELP";
