export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const SET_APPLICATION = "SET_APPLICATION";
export const SET_FOCUSED = "SET_FOCUSED";
export const REMOVE_FOCUSED = "REMOVE_FOCUSED";
export const TOGGLE_LOADING_APPLICATION = "TOGGLE_LOADING_APPLICATION";
export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";

export const GET_STAKEHOLDERS = "GET_STAKEHOLDERS";
export const CREATE_STAKEHOLDER = "CREATE_STAKEHOLDER";
export const UPDATE_STAKEHOLDER = "UPDATE_STAKEHOLDER";
export const DELETE_STAKEHOLDER = "DELETE_STAKEHOLDER";
export const TOGGLE_LOADING_STAKEHOLDERS = "TOGGLE_LOADING_STAKEHOLDERS";

export const GET_INFORMATION_ELEMENTS = "GET_INFORMATION_ELEMENTS";
export const CREATE_INFORMATION_ELEMENT = "CREATE_INFORMATION_ELEMENT";
export const UPDATE_INFORMATION_ELEMENT = "UPDATE_INFORMATION_ELEMENT";
export const DELETE_INFORMATION_ELEMENT = "DELETE_INFORMATION_ELEMENT";
export const ADD_INFORMATION_ELEMENT_ASSOCIATION =
    "ADD_INFORMATION_ELEMENT_ASSOCIATION";
export const REMOVE_INFORMATION_ELEMENT_ASSOCIATION =
    "REMOVE_INFORMATION_ELEMENT_ASSOCIATION";

export const TOGGLE_LOADING_INFORMATION_ELEMENTS =
    "TOGGLE_LOADING_INFORMATION_ELEMENTS";

export const GET_RELATIONS = "GET_RELATIONS";
export const TOGGLE_LOADING_RELATIONS = "TOGGLE_LOADING_RELATIONS";
export const ADD_STAKEHOLDER_INFORMATION_ELEMENT_RELATION =
    "ADD_STAKEHOLDER_INFORMATION_ELEMENT_RELATION";
export const REMOVE_STAKEHOLDER_INFORMATION_ELEMENT_RELATION_FROM_REDUX =
    "REMOVE_STAKEHOLDER_INFORMATION_ELEMENT_RELATION_FROM_REDUX";
export const REMOVE_STAKEHOLDER_INFORMATION_ELEMENT_RELATION =
    "REMOVE_STAKEHOLDER_INFORMATION_ELEMENT_RELATION";

export const TOGGLE_HELP = "TOGGLE_HELP";

export const SET_JSON_DATA = "SET_JSON_DATA";
export const SET_ROOT = "SET_ROOT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const TOGGLE_LOADING_AUTH = "TOGGLE_LOADING_AUTH";

export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const UPDATE_CONFIG = "UPDATE_CONFIG";
export const RESET_CONFIG = "RESET_CONFIG";
