export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const SET_APPLICATION = "SET_APPLICATION";

export const GET_STAKEHOLDERS = "GET_STAKEHOLDERS";
export const SET_LOADING_STAKEHOLDERS = "SET_LOADING_STAKEHOLDERS";
export const GET_INFORMATION_ELEMENTS = "GET_INFORMATION_ELEMENTS";
export const SET_LOADING_INFORMATION_ELEMENTS =
    "SET_LOADING_INFORMATION_ELEMENTS";
export const GET_RELATIONS = "GET_RELATIONS";
export const SET_LOADING_RELATIONS = "SET_LOADING_RELATIONS";
